#############################################################################
# Makefile for building: libCVEDSP.a
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? 11? 20 08:26:37 2013
# Project:  CVEDSP.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile CVEDSP.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -pipe -O3 -msse -ffast-math -lm -O2 -fPIC -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I.
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Tester.c \
		Plot.c \
		Interpolation.c \
		FrameProcessor.c \
		DFT/StaticRev.c \
		DFT/StaticFFT_Small.c \
		DFT/StaticFFT_9.c \
		DFT/StaticFFT_8.c \
		DFT/StaticFFT_7.c \
		DFT/StaticFFT_6.c \
		DFT/StaticFFT_5.c \
		DFT/SplitRadixGen.c \
		DFT/SplitRadix.c \
		DFT/Radix2Gen.c \
		DFT/Radix2.c \
		DFT/FFT.c \
		DFT/DFT.c \
		IntrinUtil/Memory.c \
		IntrinUtil/LogicArray.c \
		IntrinUtil/IntArray.c \
		IntrinUtil/FloatArray.c \
		IntrinUtil/Calculation.c \
		RUtil/Memory.c \
		RUtil/IO/Wave.c \
		RUtil/IO/StringStream.c \
		RUtil/IO/FileUtil.c \
		RUtil/IO/FileStream.c \
		RUtil/Misc/Converter.c \
		RUtil/Structure/String.c \
		DSPBase/Spectrum.c \
		DSPBase/Filter.c \
		DSPBase/ControlPointFilter.c \
		DSPBase/Window.c \
		DSPBase/TDEffects.c \
		DSPBase/TDAnalysis.c \
		DSPBase/LinearWarping.c \
		DSPBase/LPC.c \
		Algorithm/FECSOLA.c \
		Algorithm/PSOLA.c \
		Algorithm/Formant.c \
		Algorithm/FECSOLA.c \
		Algorithm/BaseFreq.c \
		Algorithm/SpeechDetector.c \
		DFT/StaticRadix.c 
OBJECTS       = Tester.o \
		Plot.o \
		Interpolation.o \
		FrameProcessor.o \
		StaticRev.o \
		StaticFFT_Small.o \
		StaticFFT_9.o \
		StaticFFT_8.o \
		StaticFFT_7.o \
		StaticFFT_6.o \
		StaticFFT_5.o \
		SplitRadixGen.o \
		SplitRadix.o \
		Radix2Gen.o \
		Radix2.o \
		FFT.o \
		DFT.o \
		Memory.o \
		LogicArray.o \
		IntArray.o \
		FloatArray.o \
		Calculation.o \
		Memory.o \
		Wave.o \
		StringStream.o \
		FileUtil.o \
		FileStream.o \
		Converter.o \
		String.o \
		Spectrum.o \
		Filter.o \
		ControlPointFilter.o \
		Window.o \
		TDEffects.o \
		TDAnalysis.o \
		LinearWarping.o \
		LPC.o \
		FECSOLA.o \
		PSOLA.o \
		Formant.o \
		FECSOLA.o \
		BaseFreq.o \
		SpeechDetector.o \
		StaticRadix.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CVEDSP.pro
QMAKE_TARGET  = CVEDSP
DESTDIR       = 
TARGET        = libCVEDSP.a

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET) 

staticlib: $(TARGET)

$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)


Makefile: CVEDSP.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile CVEDSP.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/staticlib.prf:
/usr/share/qt4/mkspecs/features/static.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile CVEDSP.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CVEDSP1.0.0 || $(MKDIR) .tmp/CVEDSP1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CVEDSP1.0.0/ && (cd `dirname .tmp/CVEDSP1.0.0` && $(TAR) CVEDSP1.0.0.tar CVEDSP1.0.0 && $(COMPRESS) CVEDSP1.0.0.tar) && $(MOVE) `dirname .tmp/CVEDSP1.0.0`/CVEDSP1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CVEDSP1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Tester.o: Tester.c Tester.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Tester.o Tester.c

Plot.o: Plot.c Plot.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Plot.o Plot.c

Interpolation.o: Interpolation.c Interpolation.h \
		IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Interpolation.o Interpolation.c

FrameProcessor.o: FrameProcessor.c FrameProcessor.h \
		DSPBase/Window.h \
		IntrinUtil/FloatArray.h \
		DFT/FFT.h \
		DFT/StaticRev.h \
		DFT/SplitRadix.h \
		DSPBase/Filter.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FrameProcessor.o FrameProcessor.c

StaticRev.o: DFT/StaticRev.c DFT/StaticRev.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticRev.o DFT/StaticRev.c

StaticFFT_Small.o: DFT/StaticFFT_Small.c DFT/StaticFFT_Small.h \
		DFT/FFTCommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticFFT_Small.o DFT/StaticFFT_Small.c

StaticFFT_9.o: DFT/StaticFFT_9.c DFT/StaticFFT_9.h \
		DFT/FFTCommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticFFT_9.o DFT/StaticFFT_9.c

StaticFFT_8.o: DFT/StaticFFT_8.c DFT/StaticFFT_8.h \
		DFT/FFTCommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticFFT_8.o DFT/StaticFFT_8.c

StaticFFT_7.o: DFT/StaticFFT_7.c DFT/StaticFFT_9.h \
		DFT/FFTCommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticFFT_7.o DFT/StaticFFT_7.c

StaticFFT_6.o: DFT/StaticFFT_6.c DFT/StaticFFT_6.h \
		DFT/FFTCommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticFFT_6.o DFT/StaticFFT_6.c

StaticFFT_5.o: DFT/StaticFFT_5.c DFT/StaticFFT_5.h \
		DFT/FFTCommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticFFT_5.o DFT/StaticFFT_5.c

SplitRadixGen.o: DFT/SplitRadixGen.c DFT/SplitRadixGen.h \
		DFT/SplitRadix.h \
		IntrinUtil/Calculation.h \
		DFT/DFT.h \
		DFT/FFTCommon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o SplitRadixGen.o DFT/SplitRadixGen.c

SplitRadix.o: DFT/SplitRadix.c DFT/SplitRadix.h \
		IntrinUtil/Calculation.h \
		DFT/DFT.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o SplitRadix.o DFT/SplitRadix.c

Radix2Gen.o: DFT/Radix2Gen.c DFT/Radix2Gen.h \
		IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Radix2Gen.o DFT/Radix2Gen.c

Radix2.o: DFT/Radix2.c DFT/Radix2.h \
		IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Radix2.o DFT/Radix2.c

FFT.o: DFT/FFT.c DFT/FFT.h \
		DFT/StaticRev.h \
		DFT/SplitRadix.h \
		DFT/DFT.h \
		DFT/StaticFFT_9.h \
		DFT/StaticFFT_8.h \
		DFT/StaticFFT_7.h \
		DFT/StaticFFT_6.h \
		DFT/StaticFFT_5.h \
		DFT/StaticFFT_Small.h \
		DFT/StaticRadix.h \
		DFT/FFTBlock.h \
		DFT/FFTCommon.h \
		IntrinUtil/Memory.h \
		IntrinUtil/FloatArray.h \
		IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FFT.o DFT/FFT.c

DFT.o: DFT/DFT.c DFT/DFT.h \
		IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o DFT.o DFT/DFT.c

Memory.o: IntrinUtil/Memory.c IntrinUtil/Memory.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Memory.o IntrinUtil/Memory.c

LogicArray.o: IntrinUtil/LogicArray.c IntrinUtil/LogicArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LogicArray.o IntrinUtil/LogicArray.c

IntArray.o: IntrinUtil/IntArray.c IntrinUtil/IntArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o IntArray.o IntrinUtil/IntArray.c

FloatArray.o: IntrinUtil/FloatArray.c IntrinUtil/FloatArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FloatArray.o IntrinUtil/FloatArray.c

Calculation.o: IntrinUtil/Calculation.c IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Calculation.o IntrinUtil/Calculation.c

Memory.o: RUtil/Memory.c ../Rocaloid/RUtil/Memory.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Memory.o RUtil/Memory.c

Wave.o: RUtil/IO/Wave.c ../Rocaloid/RUtil/IO/Wave.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Structure/Array.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Wave.o RUtil/IO/Wave.c

StringStream.o: RUtil/IO/StringStream.c ../Rocaloid/RUtil/IO/StringStream.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Structure/Array.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StringStream.o RUtil/IO/StringStream.c

FileUtil.o: RUtil/IO/FileUtil.c ../Rocaloid/RUtil/IO/FileUtil.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/IO/Wave.h \
		../Rocaloid/RUtil/Structure/Array.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FileUtil.o RUtil/IO/FileUtil.c

FileStream.o: RUtil/IO/FileStream.c ../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Structure/Array.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FileStream.o RUtil/IO/FileStream.c

Converter.o: RUtil/Misc/Converter.c ../Rocaloid/RUtil/Structure/String.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Converter.o RUtil/Misc/Converter.c

String.o: RUtil/Structure/String.c ../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Structure/Array.h \
		RUtil/Memory.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o String.o RUtil/Structure/String.c

Spectrum.o: DSPBase/Spectrum.c DSPBase/Spectrum.h \
		DSPBase/ControlPointFilter.h \
		RUtil/RUtil.h \
		../Rocaloid/RUtil/Structure/Array.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Misc/Converter.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/IO/StringStream.h \
		DSPBase/Filter.h \
		Algorithm/Formant.h \
		IntrinUtil/FloatArray.h \
		IntrinUtil/Calculation.h \
		DFT/FFT.h \
		DFT/StaticRev.h \
		DFT/SplitRadix.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Spectrum.o DSPBase/Spectrum.c

Filter.o: DSPBase/Filter.c DSPBase/Filter.h \
		DFT/FFT.h \
		DFT/StaticRev.h \
		DFT/SplitRadix.h \
		IntrinUtil/FloatArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Filter.o DSPBase/Filter.c

ControlPointFilter.o: DSPBase/ControlPointFilter.c DSPBase/ControlPointFilter.h \
		RUtil/RUtil.h \
		../Rocaloid/RUtil/Structure/Array.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Misc/Converter.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/IO/StringStream.h \
		IntrinUtil/FloatArray.h \
		Interpolation.h \
		DSPBase/Filter.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ControlPointFilter.o DSPBase/ControlPointFilter.c

Window.o: DSPBase/Window.c DSPBase/Window.h \
		IntrinUtil/Calculation.h \
		IntrinUtil/FloatArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Window.o DSPBase/Window.c

TDEffects.o: DSPBase/TDEffects.c DSPBase/TDEffects.h \
		IntrinUtil/FloatArray.h \
		IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o TDEffects.o DSPBase/TDEffects.c

TDAnalysis.o: DSPBase/TDAnalysis.c DSPBase/TDAnalysis.h \
		IntrinUtil/FloatArray.h \
		IntrinUtil/Calculation.h \
		DFT/FFT.h \
		DFT/StaticRev.h \
		DFT/SplitRadix.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o TDAnalysis.o DSPBase/TDAnalysis.c

LinearWarping.o: DSPBase/LinearWarping.c DSPBase/LinearWarping.h \
		../Rocaloid/RUtil/RUtil.h \
		../Rocaloid/RUtil/Structure/Array.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Misc/Converter.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/IO/StringStream.h \
		IntrinUtil/FloatArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinearWarping.o DSPBase/LinearWarping.c

LPC.o: DSPBase/LPC.c DSPBase/LPC.h \
		IntrinUtil/FloatArray.h \
		IntrinUtil/Calculation.h \
		DSPBase/Spectrum.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LPC.o DSPBase/LPC.c

FECSOLA.o: Algorithm/FECSOLA.c Algorithm/FECSOLA.h \
		Algorithm/PSOLA.h \
		RUtil/RUtil.h \
		../Rocaloid/RUtil/Structure/Array.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Misc/Converter.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/IO/StringStream.h \
		DSPBase/ControlPointFilter.h \
		../Rocaloid/RUtil/RUtil.h \
		DSPBase/Filter.h \
		IntrinUtil/FloatArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FECSOLA.o Algorithm/FECSOLA.c

PSOLA.o: Algorithm/PSOLA.c Algorithm/PSOLA.h \
		RUtil/RUtil.h \
		../Rocaloid/RUtil/Structure/Array.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Misc/Converter.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/IO/StringStream.h \
		IntrinUtil/FloatArray.h \
		FrameProcessor.h \
		DSPBase/Filter.h \
		DSPBase/TDEffects.h \
		Algorithm/SpeechDetector.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o PSOLA.o Algorithm/PSOLA.c

Formant.o: Algorithm/Formant.c Algorithm/Formant.h \
		DSPBase/Filter.h \
		DSPBase/LPC.h \
		DSPBase/Spectrum.h \
		DFT/FFT.h \
		DFT/StaticRev.h \
		DFT/SplitRadix.h \
		DSPBase/Window.h \
		IntrinUtil/FloatArray.h \
		IntrinUtil/Calculation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o Formant.o Algorithm/Formant.c

FECSOLA.o: Algorithm/FECSOLA.c Algorithm/FECSOLA.h \
		Algorithm/PSOLA.h \
		RUtil/RUtil.h \
		../Rocaloid/RUtil/Structure/Array.h \
		../Rocaloid/RUtil/Structure/String.h \
		../Rocaloid/RUtil/Misc/Converter.h \
		../Rocaloid/RUtil/IO/FileStream.h \
		../Rocaloid/RUtil/IO/StringStream.h \
		DSPBase/ControlPointFilter.h \
		../Rocaloid/RUtil/RUtil.h \
		DSPBase/Filter.h \
		IntrinUtil/FloatArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FECSOLA.o Algorithm/FECSOLA.c

BaseFreq.o: Algorithm/BaseFreq.c Algorithm/BaseFreq.h \
		DSPBase/Filter.h \
		DSPBase/Spectrum.h \
		DSPBase/Window.h \
		DFT/FFT.h \
		DFT/StaticRev.h \
		DFT/SplitRadix.h \
		IntrinUtil/Calculation.h \
		IntrinUtil/FloatArray.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o BaseFreq.o Algorithm/BaseFreq.c

SpeechDetector.o: Algorithm/SpeechDetector.c Algorithm/SpeechDetector.h \
		DSPBase/Spectrum.h \
		DSPBase/Filter.h \
		DSPBase/TDEffects.h \
		FrameProcessor.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o SpeechDetector.o Algorithm/SpeechDetector.c

StaticRadix.o: DFT/StaticRadix.c DFT/StaticRadix.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o StaticRadix.o DFT/StaticRadix.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

