#include "SpeechDetector.h"
#include "DSPBase/Spectrum.h"
#include "DSPBase/Filter.h"
#include "DSPBase/TDEffects.h"
#include "FrameProcessor.h"
#include <malloc.h>

SpeechDetectorParameters SPara;

/*  Original Condition
    SPara.VoiceThreshold = 0.005;
    SPara.VolumeThreshold = 0.005;

    SPara.PreProcessLowFreq = 80;
    SPara.PreProcessHighFreqFactor = 1.5;
    SPara.PreProcessMovingAverageRatio = 0.2;

    SPara.Delay = 2;
*/

void SDetector_Init()
{
    //Generated by Genetic Optimizer
    SPara.VoiceThreshold = 0.001;
    SPara.VolumeThreshold = 0.005;

    SPara.PreProcessLowFreq = 84.502991;
    SPara.PreProcessHighFreqFactor = 1.612363;
    SPara.PreProcessMovingAverageRatio = 0.194699;

    SPara.Delay = 1.556963;
}

void SDetector_SetParameters(SpeechDetectorParameters Src)
{
    SPara = Src;
}

void SpeechDetectorPreProcess(float* Dest, float* Src, float BaseFreq, int Length)
{
    float BasePeriod = SampleRate / BaseFreq;
    float* Processed = (float*)malloc(sizeof(float) * Length + 2 * BasePeriod);
    GenerateBandPass(ProcessorTmp_Filter, SPara.PreProcessLowFreq, BaseFreq * SPara.PreProcessHighFreqFactor, 512);
    Process(Processed, Src, Processor_Filter, 10, Length);
    MovingAverage(Dest, Processed, 1, BasePeriod * SPara.PreProcessMovingAverageRatio, Length);
    free(Processed);
}

float DetectVocalOnset(float* Src, int Length)
{
    int i;
    for(i = 0; i < Length; i ++)
        if(Src[i] > SPara.VolumeThreshold || Src[i] < - SPara.VolumeThreshold)
            return (float)i / SampleRate;
    return - 1;
}

float DetectVOTWithBaseFreq(float* Src, float BaseFreq, int Length)
{
    int i, j;
    float VoiceKeepRecord = 0;
    float VoiceKeepTime = 0;
    float VoiceOnsetRecord = 0;
    float VoiceOnsetTime = - 1;
    float BasePeriod = SampleRate / BaseFreq;
    for(i = 0; i < Length - BasePeriod; i += BasePeriod)
    {
        for(j = 0; j < BasePeriod; j ++)
        {
            if(Src[i + j] > SPara.VoiceThreshold || Src[i + j] < - SPara.VoiceThreshold)
            {
                VoiceKeepTime ++;
                if(VoiceOnsetTime == -1)
                    VoiceOnsetTime = i;
                if(VoiceKeepTime > VoiceKeepRecord)
                {
                    VoiceKeepRecord = VoiceKeepTime;
                    VoiceOnsetRecord = VoiceOnsetTime + BasePeriod * SPara.Delay;
                }
                goto CheckNext;
            }
        }
        VoiceKeepTime = 0;
        VoiceOnsetTime = - 1;
        CheckNext:;
    }
    return (float)VoiceOnsetRecord / SampleRate;
}
